### ISSUE TITLE
docs: add colloquial name

### ISSUE THREAD

**Issue by oakmac** [cljsinfo/cljs.info#24]
Some core functions have a colloquial name that they are referred to by when spoken.

Examples are:
* `assoc` = associate
* `conj` = conjoin
* `def` = define

It would be nice to add an optional section to the .cljsdoc files with this information where appropriate. I'm thinking the section header could be:
===== Known As

**Comment by shaunlebron** [comment]
fixed: https://github.com/cljsinfo/cljs-api-docs/commit/777d798f8b9669eb66b83e4ba3c45e3d4a9e0a53

we can add pronunciation form in parentheses after the word if we wanted, but I left them out.
