### ISSUE TITLE
EDN Pretty Printer

### ISSUE THREAD

**Issue by oakmac** [cljsinfo/cljs.info#42]
I cannot find an EDN pretty printer online anywhere.

I have run into many situations where this sort of tool would be helpful. We should build one for the site.

NOTE: this may require the server running Java?

**Comment by oakmac** [comment]
@comamitc is working on this as a separate project: https://github.com/comamitc/pretty-print.net

**Comment by comamitc** [comment]
http://pretty-print.net/ is live.  I think you can close this.

**Comment by shaunlebron** [comment]
thanks a million @comamitc :+1:
