### ISSUE TITLE
cljs.info displays nothing with javascript disabled

### ISSUE THREAD

**Issue by NPrescott** [cljsinfo/cljs.info#46]
Yes I'm serious. 

I realize no one else cares but this may help remind me to do a pull against this with a fix of some kind.

**Comment by shaunlebron** [comment]
Google set a precedent recently to not support js-disabled browsers:

![goog-sherlock](https://i.imgur.com/wfJ5lue.png)

source: https://www.reddit.com/r/javascript/comments/3d09y7/googles_new_page_if_you_have_javascript_disabled/

**Comment by comamitc** [comment]
If we can convert to isomorphic react we can render the pages on the server so that js-disabled clients are handled. 

I tend to agree with @shaunlebron's point though, given that this is a JS transpiled language if you JS disabled and are a JS dev... LOL.

**Comment by shaunlebron** [comment]
good point
