### ISSUE TITLE
Missing 'gensym'

### ISSUE THREAD

**Issue by hura** [cljsinfo/cljs.info#53]
The cheatsheet is missing `gensym`. In general all these should be included:

https://github.com/clojure/clojurescript/blob/28a31165e837826483e7bc69d4645e7f3b67520e/devnotes/corelib.org

**Comment by shaunlebron** [comment]
thanks @hura, we'll have to figure out how to categorize these in a meaningful way.  thanks for the link

**Comment by shaunlebron** [comment]
we have docs for the following gensym things:

- [`# auto-gensym`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/syntax_auto-gensym.md)
- [`gensym`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_gensym.md)

I think the function of the cheatsheet at this point will be to include only the most common functions.  Gensym will be kept out of the cheatsheet, but all docs will be accessible from a search box, namespace browser, or tag browser.
