### ISSUE TITLE
Cannot start on my development machine

### ISSUE THREAD

**Issue by adamhunter** [cljsinfo/cljs.info#59]
Hey guys,  ran through a couple of snafus in my setup and updated the readme appropriately.  Currently I'm getting an error when running `node app.js`.  
Specifically I am getting: `Error: Cannot find module './docs.json'` 

Full error at: https://gist.github.com/adamhunter/a0a99d627d1004b4a2b3

**Comment by oakmac** [comment]
`docs.json` is generated by running `grunt build-docs` from the project root. Running `grunt watch` in the background should also build `docs.json` as any .cljsdoc file is changed.

After you get this error resolved, I suspect you will get a second error about `generated-docs.json`, which is something that we've been handling manually for now. More information here: https://github.com/shaunlebron/cljs-api-docs

It is on the shortlist to make getting started and contributing as easy as possible.

**Comment by oakmac** [comment]
Quick instructions for `generated-docs.json`:

- go to https://github.com/shaunlebron/cljs-api-docs/releases
- download latest zip
- put the `*.cljsdoc` files into a folder in the project root of this project called `docs-generated`
- run `grunt build-gen-docs`

That *should* produce a `generated-docs.json` file in the project root.

I promise we will make this process cleaner very soon :)

FYI: @shaunlebron
