### ISSUE TITLE
Any roadmap?

### ISSUE THREAD

**Issue by benzen** [cljsinfo/cljs.info#64]
I'm more than happy to participate in this effort, even if it's not much.
But i'm wondering what are we waiting before making this site alive?

I mean, you've pointed out some places where there is absolutely a need for great tutorial.
But this kind of thing can be delivered latter, in my opinion.

So is there some reason not to go live?

**Comment by shaunlebron** [comment]
Initial release is going to have the following:

- home page (100%?)
- getting started page (0%)
- cheatsheet (90%?)
- docs pages (60%?)

Chris has pending work on the docs pages design.  I'm working on the API reference generator, which I hope to wrap up in a week or so.

**Comment by benzen** [comment]
So we can assume that the site will be release in a week, or a couple of week.
Great
