### ISSUE TITLE
suggesting a hack so that popups at the bottom of the page are visible

### ISSUE THREAD

**Issue by bhauman** [cljsinfo/cljs.info#66]
If you add some extra space at the bottom of the page the popups at the bottom will be visible.

**Comment by shaunlebron** [comment]
thanks! worked well :+1:  (cc: @oakmac, publish change when you get a chance, thanks)

<img width="589" alt="screen shot 2015-07-27 at 2 57 43 pm" src="https://cloud.githubusercontent.com/assets/116838/8916284/15b034b6-3470-11e5-9c1c-551a7e6d63cd.png">
