### ISSUE TITLE
Several array functions missing

### ISSUE THREAD

**Issue by CASandmann** [cljsinfo/cljs.info#67]
I don't know exactly how many other cljs functions that aren't on the cheatsheet, but some important array functions are missing, namely `amap` `areduce` `alength` etc.  Supposedly [this pdf](http://appletree.or.kr/quick_reference_cards/Others/ClojureScript%20Cheat%20Sheet.pdf) has a more comprehensive list of functions than the cheatsheet does, but it doesn't really document them.

**Comment by shaunlebron** [comment]
our api docs have these, but we do need to add them to the cheatsheet.

- [`amap`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_amap.md)
- [`areduce`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_areduce.md)
- [`alength`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_alength.md)

**Comment by shaunlebron** [comment]
I think the cheatsheet's function is to provide the most commonly used functions.  Will reopen if this changes.
