### ISSUE TITLE
Pages infrastructure

### ISSUE THREAD

**Issue by shaunlebron** [cljsinfo/cljs.info#72]
I think most pages of the website might best be implemented through [cryogen pages](http://cryogenweb.org/docs/creating-pages.html) to allow markdown files backed by css and html templates.

It would probably allow for easier management of page content and an avenue for community-contributed pages, curated through pull requests.

These may exist as community-contributed pages:

- Tutorials
- [JavaScript synonyms](https://kanaka.github.io/clojurescript/web/synonym.html)
- [REPL page](http://clojurescript.net)
- Language spec ([was discussed here](http://clojurians-log.mantike.pro/clojurescript/2015-06-19.html)))

These contributed pages will have some overlap of content and purpose with the official ClojureScript wiki.  Perhaps the website should only have pages that should be at the forefront of a user's attention, which will require some curation of course.

**Comment by shaunlebron** [comment]
I looked into this some more and I think a static site will simplify deployment and will encourage more contributors.  It would also make it easier for the website to trade ownership over the years as well.

__Content is more important than anything else on this website__.

[React](http://facebook.github.io/react) is a good example of a static site for a popular technology that meets all its doc needs, though it's generated by a similar technology, Jekyll.

More reasons that compelled me:

- the _ClojureScript Unraveled_ book can probably be imported with ease since it is written in asciidoc, which is supported by cryogen
- we can generate markdown pages for each API/syntax doc
- simple SEO
- easy to create News posts

The API quick search will be somewhat tricky to implement with this static model, but worth it I think since it'll make everything else much easier.

**Comment by benzen** [comment]
About the Quick search, or could ne done client side. It is what github use for their help pages. If i recall correctly they open sourced their js search engine. You'll only need to provide the content of the site un an other form ( surely json)

Envoyé de mon iPhone

**Comment by shaunlebron** [comment]
thanks @benzen, will look at that.

closing this since the new [site](https://github.com/cljsinfo/site) repo handles pages really well through jekyll.
